# Generated by Django 6.0 on 2026-01-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('force_update', models.BooleanField(default=False)),
                ('os', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
            ],
        ),
    ]
