# Generated by Django 6.0 on 2026-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='download_url',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='os',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, unique=True),
        ),
    ]
