# Generated by Django 6.0 on 2026-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_appversion_download_url_alter_appversion_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='release_notes',
            field=models.TextField(blank=True),
        ),
    ]
