# Generated by Django 6.0 on 2026-01-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_appversion_release_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='min_version',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
